### ISSUE TITLE
Skitch 2.0 removes WebDAV support

### ISSUE THREAD

**Issue by matiaskorhonen** [roidrage/s3itch#6]
The latest version of Skitch (2.0) removes WebDAV support (along with support for any other non-Evernote sharing options).

As far as I can tell this is unfixable (unless WebDAV support is re-added to Skitch), but you might want to add a note about this to the README in any case?

**Comment by matiaskorhonen** [comment]
One more thing, a direct link to Skitch v1.0.12: http://www.macupdate.com/download/39932/skitch.zip

**Comment by roidrage** [comment]
Thanks for the suggestion, I added a note to the README about 2.0 and the download link you provided in 3a7e62c072
